from typing import cast, Dict, List, Optional, Union
import elasticsearch.client

class Elasticsearch:
    cluster = elasticsearch.client.ClusterClient()
    indices = elasticsearch.client.IndicesClient()

    def __init__(self, hosts: Optional[Union[str, List[str]]] = None, **kwargs) -> None: ...

    def info(self, params: Optional[Dict]=None) -> Dict: ...

class ElasticsearchException(Exception): ...
class TransportError(ElasticsearchException): ...
class NotFoundError(TransportError): ...
